include:
  package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/models/**
  plugins:
    - dart_code_metrics

linter:
  rules:
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_single_cascade_in_expression_statements
    - constant_identifier_names
    - control_flow_in_finally
    - empty_constructor_bodies
    - empty_statements
    - exhaustive_cases
    - implementation_imports
    - library_names
    - library_prefixes
    - null_closures
    - overridden_fields
    - package_names
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_is_not_operator
    - prefer_null_aware_operators
    - prefer_spread_collections
    - prefer_void_to_null
    - recursive_getters
    - slash_for_doc_comments
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
    - valid_regexps
    - always_use_package_imports
    - avoid_relative_lib_imports
    - always_declare_return_types
    - avoid_double_and_int_checks
    - avoid_empty_else
    - avoid_print
    - avoid_private_typedef_functions
    - avoid_setters_without_getters
    - avoid_shadowing_type_parameters
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cancel_subscriptions
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - file_names
    - flutter_style_todos
    - list_remove_unrelated_type
    - no_duplicate_case_values
    - non_constant_identifier_names
    - no_adjacent_strings_in_list
    - one_member_abstracts
    - only_throw_errors
    - package_api_docs
    - parameter_assignments
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_asserts_with_message
    - prefer_asserts_in_initializer_lists
    - package_prefixed_library_names
    - prefer_final_in_for_each
    - prefer_final_locals
    - provide_deprecation_message
    - prefer_foreach
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_typing_uninitialized_variables
    - sort_child_properties_last
    - sort_constructors_first
    - use_setters_to_change_properties
    - use_string_buffers
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - throw_in_finally
    - type_annotate_public_apis
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unrelated_type_equality_checks
    - unsafe_html
    - use_full_hex_values_for_flutter_colors
    - use_to_and_as_if_applicable
    - void_checks
    - always_put_control_body_on_new_line
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_field_initializers_in_const_classes
    - hash_and_equals
    - literal_only_boolean_expressions
    - join_return_with_assignment
    - invariant_booleans
    - avoid_classes_with_only_static_members
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_positional_boolean_parameters
    - avoid_returning_null
    - avoid_returning_this
    - avoid_returning_null_for_future
    - avoid_types_on_closure_parameters
    - omit_local_variable_types
    - prefer_generic_function_type_aliases
    - prefer_interpolation_to_compose_strings
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_single_quotes
    - iterable_contains_unrelated_type
    - empty_catches
#    - public_member_api_docs
#    - avoid_catches_without_on_clauses
#    - lines_longer_than_80_chars

#dart_code_metrics:
#  anti-patterns:
#    - long-method
#    - long-parameter-list
#  metrics:
#    cyclomatic-complexity: 20
#    maximum-nesting-level: 5
#    number-of-parameters: 4
#    source-lines-of-code: 50
#  metrics-exclude:
#    - test/**
#  rules:
#    - newline-before-return
#    - no-boolean-literal-compare
#    - no-empty-block
##    - prefer-trailing-comma
#    - prefer-conditional-expressions
#    - no-equal-then-else