query branchesList($owner: String!, $repo: String!, $first: Int!, $after: String, $query: String) {
  repository(name: $repo, owner: $owner) {
    refs(
      first: $first
      after: $after
      query: $query
      refPrefix: "refs/heads/"
      orderBy: {field: ALPHABETICAL, direction: ASC}
    ) {
      edges {
        cursor
        node {
          name
          id
          target {
            __typename
            ... on Commit {
              oid
              abbreviatedOid
              commitUrl
              url
              committedDate
            }
          }
          branchProtectionRule {
            isAdminEnforced
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}

